[package]
name = "nft_image_proxy"
version = "1.4.0"
authors = ["Cryptonomic Inc."]
edition = "2018"
build = "build.rs"

[build-dependencies]
built = { version = "0.5", features = ["git2"] }

[dependencies]
hyper = { version = "0.14", features = ["full"] }
hyper-timeout = "0.4"
tokio = { version = "1", features = ["full"] }
log = "0.4"
log4rs = "1"
hocon = "0.7"
sha2 = "0.9"
hex = "0.4"
base64 = "0.13"
hyper-tls = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
prometheus = { version = "0.13", features = ["process"] }
lazy_static = "1.4"
bb8 = "0.7"
bb8-postgres = "0.7"
tokio-postgres = { version="0.7", features=["with-chrono-0_4"] }
async-trait = "0.1"
image = "0.23"
dns-lookup = "1"
anyhow = "1.0"
rust-embed="6.3"
jemallocator = { version = "0.3", optional = true }

# deps for aws
aws-config = "0.0.26-alpha"
aws-sdk-rekognition = "0.0.26-alpha"
aws-sdk-s3 = "0.0.26-alpha"
aws-types = "0.0.26-alpha"

# Overrides to address vulns
time = "0.3"

[profile.release]
lto = true

[features]
default = ["jemalloc"]
jemalloc = ["jemallocator"]