[package]
name = "nft_image_proxy"
version = "1.4.1"
authors = ["Cryptonomic Inc."]
edition = "2018"
build = "build.rs"
exclude = ["/docker", "/docs", "/lib", "/log", "proxy.conf", "/*.yml", "/.github", "Dockerfile", "LICENSE", "README.md", ".gitignore", ".dockerignore"]

[build-dependencies]
built = { version = "0.5", features = ["git2"] }

[dependencies]
hyper = { version = "0.14", features = ["full"] }
hyper-timeout = "0.4"
tokio = { version = "1", features = ["full"] }
log = "0.4"
log4rs = "1"
hocon = "0.7"
sha2 = "0.10"
hex = "0.4"
base64 = "0.13"
hyper-tls = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
prometheus = { version = "0.13", features = ["process"] }
lazy_static = "1.4"
bb8 = "0.7"
bb8-postgres = "0.7"
tokio-postgres = { version="0.7", features=["with-chrono-0_4"] }
async-trait = "0.1"
image = "0.23"
dns-lookup = "1"
anyhow = "1.0"
rust-embed="6.3"

# deps for aws
aws-config = "0.6.0"
aws-sdk-rekognition = "0.6.0"
aws-sdk-s3 = "0.6.0"
aws-types = "0.6.0"

# Overrides to address vulns
time = "0.3"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version="0.4", features=[ "background_threads_runtime_support", "background_threads"] }


[dev-dependencies]
rand = "0.8.4"

[profile.release]
lto = true

[features]