[package]
name = "nft_image_proxy"
version = "1.1.0"
authors = ["Cryptonomic Inc."]
edition = "2018"
build = "build.rs"

[build-dependencies]
built = { version = "0.5", features = ["git2"] }

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
log = "0.4.14"
log4rs = "1.0.0"
hocon = "0.5.1"
rust-crypto = "0.2.36"
base64 = "0.13.0"
rustc-serialize = "0.3.24"
hyper-tls = "0.5.0"
serde = { version = "1", features = ["derive"] }
serde_json = "^1.0.59"
chrono = "0.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
prometheus = { version = "0.9", features = ["process"] }
lazy_static = "1.4"
bb8 = "0.7.0"
bb8-postgres = "0.7.0"
tokio-postgres = { version="0.7.2", features=["with-chrono-0_4"] }
procfs = "0.9.1"
async-trait = "0.1.50"
image = "0.23.14"
dns-lookup = "1.0.7"
ipnet = { version = "2", features = ["serde"] }

[profile.release]
lto = true