version: "3"

services:
  proxy:
    #image: ${IMG_PROXY_DOCKER_IMAGE:-cryptonomictech/nft-image-proxy:latest}
    build: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    networks:
      - proxy-net
    ports:
      - ${PORT:-3000}:3000
    volumes:
      - "${PROXY_CONFIG_PATH:-./proxy.conf}:/opt/img_proxy/proxy.conf"
      - "${PROXY_LOG_CONFIG_PATH:-./log4rs.yml}:/opt/img_proxy/log4rs.yml"
      - "sql:/opt/img_proxy/sql"
      - "${PROXY_LOG_PATH:-./log}:/opt/img_proxy/log"
    depends_on:
      - database

  database:
    image: "postgres:13.3"
    environment:
      POSTGRES_USER: "imgproxy"
      POSTGRES_PASSWORD: "super_long_password_change_me!"
      POSTGRES_DB: "imgproxy"
    networks:
      - proxy-net
    expose:
      - 5432
    volumes:
      - database-data:/var/lib/postgresql/data/
      - "sql:/docker-entrypoint-initdb.d/"

volumes:
  database-data:
  sql:

networks:
  proxy-net:
    driver: bridge
