name: build

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ~/.cargo/bin            
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-proxy-cache-${{ hashFiles('Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: build
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ./lib/npm/node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('lib/npm/package-lock.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
        working-directory: ./lib/npm
      - run: npm run build
        working-directory: ./lib/npm
