name: build-libs

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ./lib/npm/node_modules
          key: ${{ runner.os }}-lib-cache-${{ hashFiles('lib/npm/package-lock.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
        working-directory: ./lib/npm
      - run: npm run build
        working-directory: ./lib/npm
