name: Publish artifacts

on:
  workflow_dispatch:
    inputs:
      tag_as_latest:
        description: "Tag image as latest"
        required: true
        default: false
        type: boolean

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: cryptonomictech/nft-image-proxy
          tags: |
            type=semver,pattern={{version}}
      - run: echo "IMAGE_TAGS=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV
      - run: echo "IMAGE_TAGS=\"${{ env.IMAGE_TAGS }},cryptonomictech/nft-image-proxy:latest\"" >> $GITHUB_ENV
        if: ${{ github.event.inputs.tag_as_latest == 'true' }}
      - name: Validate image tags
        run: |
          echo "Publishing requires a semver compliant git tag"
          exit 1
        if: steps.meta.outputs.tags == ''
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
